[general]
# import = ["/nix/store/xzhsfnwcmcra9njyl99vzapfq75rdd1w-alacritty-theme-0-unstable-2024-10-24/kanagawa_wave.toml"]
import = ["/Users/qkniep/.config/alacritty/themes/everblush.toml"]
live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutExpo"
color = "#918175"
duration = 250

[cursor]
style = "Block"
unfocused_hollow = true
vi_mode_style = "Block"

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[font]
size = 15

[font.bold]
family = "MonaspiceNe Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MonaspiceNe Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MonaspiceNe Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MonaspiceNe Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "None"
dynamic_title = true
